### ISSUE TITLE
Issue: Photo not properly scaled

### ISSUE THREAD

**Issue by Synt3x** [bpatrik/pigallery2#234] opened 2021-03-10 19:56 UTC
**Issue description:**
I notice that a lot of photo that is being showed in the gallery view isn't properly scaled. But if you view the thumbnail on the landing page then it's scaled properly.

Update:
The issue seems to only occur on photo taken vertical and not horizontal. 
Update2:
Seems like photo taken with iOS portrait-mode isn't effected by this issue, but all taken with vertical mode is. Seems like the photo-tool doesn't know that it's taken vertical and scales it incorrectly.

**Screenshots:**
1) - landing page (image 1 is being scaled properly here)
![image_issue_000](https://user-images.githubusercontent.com/11620295/110689244-c3a69b80-81e2-11eb-9fcd-5e90422fa0d2.png)

2) - gallery (image 1 is not scaled properly, but image 2 is)
![image_issue_001](https://user-images.githubusercontent.com/11620295/110689271-cb664000-81e2-11eb-9a0a-aae912fb4c29.png)

**Environment:**
 - OS: Server, Ubuntu/Docker:latest - Client, Windows 10 20H2
 - Browser: Firefox 86.0 64bit
 - Photo: Happens with both iPhone X and iPhone 11 (native camera app)

**Other:**
If you have any questions or want me to do anything else for testing please let me know. (Haven't tested the nightly build, because it didn't seemed that any commit fixed this issue)

**Comment by lbischof** [comment] 2021-03-13 14:39
This is a duplicate of #212 and can be fixed by correcting the exif rotation data. A tool that can help is https://github.com/Matthias-Wandel/jhead You can run `jhead -autorot img.jpg`

**Comment by Synt3x** [comment] 2021-03-13 14:49
Is there nothing that could be done in PiGallery? When displaying the full photo its not laying down. Couldn't the PiGallery automatically solve this when displaying the thumbnail?

**Comment by bpatrik** [comment] 2021-03-14 16:11
I working on #58. Once the advanced search is stable I will this and  #212.

In the meantime, feel free to jump in.
Most likely the issue is with this function: https://github.com/bpatrik/pigallery2/blob/ddf5b256f9ea4ce37ec40292959624b4b49d38e6/src/backend/model/threading/MetadataLoader.ts#L88

You can test it with:
in a "`test.ts`":
```
 import {MetadataLoader} from './src/backend/model/threading/MetadataLoader';
 MetadataLoader
   .loadPhotoMetadata('<a photo path>')
   .then(console.log).catch(console.error);
```
(of course you need nodejs and typescript compilation for this to work.)

If someone manages to fix it, please add a test here: https://github.com/bpatrik/pigallery2/blob/ddf5b256f9ea4ce37ec40292959624b4b49d38e6/test/backend/unit/model/threading/MetaDataLoader.spec.ts
I will merge the PR.

**Comment by bpatrik** [comment] 2021-03-27 09:46
Lets keep the conversation in #212. Closing this as it a duplicate.

**Closed** 2021-03-27 09:47 UTC
Labels: bug, duplicate
