### ISSUE TITLE
Option to dock header to top of page when scrolling up.

### ISSUE THREAD

**Issue by greenerk** [bpatrik/pigallery2#555] opened 2022-11-15 17:21 UTC
It's lovely to have the GUI "clear out" when scrolling down through my photos/videos, but it can be a pain having to scroll aaaaaaall the way up to navigate the breadcrumbs again.

Having an option to "dock" the header (navbar ?) to the top of the page, when you start to scroll up, would be a big improvement to the experience.

**Comment by andiohn** [comment] 2022-11-18 05:36
I agree!

**Comment by bpatrik** [comment] 2022-12-10 00:03
sort of duplicate of #27

**Closed** 2022-12-10 00:04 UTC
