### ISSUE TITLE
Issue: Map on main page block features

### ISSUE THREAD

**Issue by maarlo** [bpatrik/pigallery2#226] opened 2021-02-14 21:17 UTC
Hello, I have been using PiGalley with and iPhone and iPad (I do not test with Android devices), and it seems that map feature in main page disallow using the app, I mean, pictures can't be opened, language can't be changed, menu can't be opened. On the other hand, if Map feature is disabled, the app works properly.

I could probably z-index issue of the map ? I don't know, If I get more info I will added to this issue.

Thanks for the app and your support.

**Comment by bpatrik** [comment] 2021-02-23 13:09
Thanks for the report. 
this might be related to this: #206 and maybe this #155 ?

I'll try to look into it, but any help, contribution is welcome. 
The main issue is that I do not actively use any apple product, so I do not see these issues.

**Comment by bpatrik** [comment] 2021-04-02 09:15
I took a look on an older Ipad (Ipad Air, 12.4.4) and it kinda worked. I had to double tap on the photos to show up in the big preview (first only only brought up the black info bar). The buttons does not work in the preview, but you can navigate with swipes. 

Can you provide more details about your issue?

**Comment by maarlo** [comment] 2021-04-02 09:27
Yes of course. On that pages where the map icon is showed, the actions like openning the menu (upper right corner), open photo preview and even changing the folder are not working. It is like there is a handler of click event and a stopPropagation, because on HTML is selected (the link is underscored) but not doing what is supposed that must do.

**Comment by bpatrik** [comment] 2021-04-04 07:34
This is a duplicate of #155. Lets continue it there.

**Closed** 2021-04-04 07:34 UTC
Labels: bug
