### ISSUE TITLE
Filtering of photo's based on EXIF/XMP-tags

### ISSUE THREAD

**Issue by jurjendejong** [bpatrik/pigallery2#217] opened 2021-01-04 22:23 UTC
I absolutely love this gallery! I like to be able to share and browse my photo's very easily!

As usually I prefer to show selections I have now written a python script to make a copy of my photos folder with only the 'XMP:rating > 1'.  It would be great to have functionality in PiGallery2 to do this filtering on the go.

I see multiple possible implementations:
1. Global setting while scanning to only index when given syntax (like XMP:rating> 1) is satisfied.
2. Next to the current implementation of the sorting options, include the option to apply a filter. Either with pregiven option (rating >= 1, ...) or a field where advanced users can type a filter based on XMP/EXIF-syntax.
3. Within the (regular) search field allow filtering of the current directory.

I think this would be nice added feature. At least for my work flow. But not at all blocking for usage. As an alternative I might actually decide to run two galleries on my server ('all photos', 'rated photos')

**Comment by bpatrik** [comment] 2021-01-05 19:35
Hi this is a duplicate of #69

**Comment by bpatrik** [comment] 2021-01-05 19:36
I'm happy that you like it :)

I added rating support on the model level and try to look into the advanced search #58.

**Comment by jurjendejong** [comment] 2021-01-09 17:48
Thanks for the quick response. Sorry, I had not found the issues you mentioned. 

I'm not fully sure if the 'advanced search' works well for filtering in the current directory, as the search functionality seems to be always global (for the entire database).

**Comment by bpatrik** [comment] 2021-01-10 21:22
True. I can add an option to restrict the directory too.
So like `John in directory: /All Photos/2010/My favorites`. For absolute path Or just `John in directory: favorites` to search in any `favorite˛` folder. 

Not sure about the timeline. I would not expect a full solution within a month.

**Comment by bpatrik** [comment] 2021-05-04 21:00
Advanced search is part of the app since the latest release.
That should cover this feature request.

**Comment by bpatrik** [comment] 2021-05-04 21:00
Feel free to reopen if you still miss something.

**Closed by bpatrik** 2021-05-04 21:00 UTC
Labels: enhancement

**Comment by jurjendejong** [comment] 2021-12-12 10:55
I realized that I never responded, but the functionality works great. Thanks again!
