### ISSUE TITLE
Log shows SQL syntax error

### ISSUE THREAD

**Issue by Magneticdud** [bpatrik/pigallery2#244] opened 2021-04-01 10:15 UTC
**Description**
I get this errors in the log from docker. Looks like nothing is broken. Maybe it can be ignored?

**Environment:**
 - OS: Ubuntu - Docker:latest with database mysql

```
pigallery2    | QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' '', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAU...' at line 1
pigallery2    |     at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
pigallery2    |     at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45)
pigallery2    |     at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
pigallery2    |     at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
pigallery2    |     at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
pigallery2    |     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
pigallery2    |     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
pigallery2    |     at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
pigallery2    |     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
pigallery2    |     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16) {
pigallery2    |   code: 'ER_PARSE_ERROR',
pigallery2    |   errno: 1064,
pigallery2    |   sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' '', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAU...' at line 1",
pigallery2    |   sqlState: '42000',
pigallery2    |   index: 0,
pigallery2    |   sql: "INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, 'Senza titolo10.jpg', 'PhotoEntity', 55, DEFAULT, 1052231094000, 931932, DEFAULT, 1, DEFAULT, DEFAULT, 1783, 1200, , '', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)",
pigallery2    |   query: 'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, ?, ?, ?, DEFAULT, ?, ?, DEFAULT, ?, DEFAULT, DEFAULT, ?, ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)',
pigallery2    |   parameters: [
pigallery2    |     'Senza titolo10.jpg',
pigallery2    |     'PhotoEntity',
pigallery2    |     55,
pigallery2    |     1052231094000,
pigallery2    |     931932,
pigallery2    |     1,
pigallery2    |     1783,
pigallery2    |     1200,
pigallery2    |     [],
pigallery2    |     '',
pigallery2    |     ''
pigallery2    |   ]
pigallery2    | }
```

**Comment by bpatrik** [comment] 2021-04-01 10:27
Hi


I think that particular photo does not get saved to the dB (won't get
listed on the UI eventually [should disappear if you empty session storage
and refreshes the site]).

If it's not too private can you send me the photo.that produces the error?

-- Sorry for being brief, sent from my phone.

Magneticdud ***@***.***> ezt írta (időpont: 2021. ápr. 1., Cs
12:16):

**Comment by Magneticdud** [comment] 2021-04-01 10:33
Well luckily the photo mentioned there is not private - I hope github doesn't change the exif if i upload it in this way
![Senza titolo10](https://user-images.githubusercontent.com/2940598/113281777-4ef8e580-92e6-11eb-8849-e7c356c707ce.jpg)

I had many of this syntax errors (100+) though

**Comment by bpatrik** [comment] 2021-04-01 17:28
Thanks. I will take a look.

I think it is related to #245 #246
And probably some of your photos contain some unexpected exif data

-- Sorry for being brief, sent from my phone.

Magneticdud ***@***.***> ezt írta (időpont: 2021. ápr. 1., Cs
12:33):

**Comment by bpatrik** [comment] 2021-04-01 20:20
Hi,

I looked into it. Unfortunately I could not reproduce it. I saw that when my app reads your photo, it thinks that the iso is `[]` (empty array) and should be an `uint32` instead. For some reason that is ok both my mysql db and sqlite sb. I guess that is the issue with your maria db. 
I fixed that hopefully it fixes your issue.

**Comment by Magneticdud** [comment] 2021-04-01 21:28
I am using mariadb:latest (docker) 

I wanted to initially use mysql 8 but the server was rejecting the client authentication (I saw there was an issue with the node mysql.js, not your fault)

**Comment by bpatrik** [comment] 2021-04-04 10:09
This should be fixed now (with the latest nightly). Closing this. Feel free to reopen if it is still failing.

**Closed by bpatrik** 2021-04-04 10:09 UTC
Labels: bug

**Comment by Magneticdud** [comment] 2021-04-04 10:38
I confirm that with pigallery2:nightly-buster it managed to index all the previously problematic images without a single error

I can't believe I'm running a snappy gallery of 50k+ photos on an orange pi with just 512mb ram ❤😍
