### ISSUE TITLE
RAW (NEF) file support

### ISSUE THREAD

**Issue by jezikk82** [bpatrik/pigallery2#300] opened 2021-05-13 10:08 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add possibility to show preview of the RAW image files (e.g. NEF, CR2).
Solution is to use embedded jpg preview (usually small size) or convert it to jpg (preferred).

**Comment by bpatrik** [comment] 2021-05-14 08:19
This is a duplicate of #127
Lets continue the discussion there.

**Closed by bpatrik** 2021-05-14 08:19 UTC
