### ISSUE TITLE
[Feature] Be able to create albums

### ISSUE THREAD

**Issue by Satris404** [bpatrik/pigallery2#139] opened 2020-02-26 01:32 UTC
I have pictures of the same trip scattered around different folders in my server. It happens when I have media exported from different devices or that have been sent from different persons. I want to keep them that way so they don't mix up.  

A nice solution would be having another tab beside "Gallery" named "Albums" that when clicked, displays all the albums saved on the server. I don't think I have to explain how the user would be able to create albums as it is a common feature you can find on a media server software. Some settings could be accessible to decide which account role can create, view or edit albums and if the albums are accessible from all accounts.

**Comment by bpatrik** [comment] 2020-02-28 22:33
Hi,

this is related to: #104, #38 and #45.

In general I don't mind adding logical folders that collect for example certain tags or other properties of photos, but I don't want to add full album support. The aim of this app is to follow the directory structure instead of using albums. There are many other libraries that do the other way around like lychee, piwigo, etc.

**Comment by Forza-tng** [comment] 2020-07-31 10:22
Hi @bpatrik, What Pigallery does better than any of the other is the amazing speed :)

I discovered that you can search for any tag, just not faces. This is really great and i haven't seen this in Piwigo. With Pigallery i can tag my photos in Digikam and they becomes searchable right away!

**Comment by bpatrik** [comment] 2020-09-06 14:17
Rereading this, it seems to be a duplicate of #45, so closing this one.

**Closed by bpatrik** 2020-09-06 14:17 UTC
Labels: enhancement
