### ISSUE TITLE
Safari bug when showing pictures on the map

### ISSUE THREAD

**Issue by LorenzoMcMaster** [bpatrik/pigallery2#653] opened 2023-04-12 16:19 UTC
When clicking on a map picture icon using safari Version 16.4 (18615.1.26.11.23) on MacOs 13.3, the picture is not displayed.

**Comment by bpatrik** [comment] 2023-04-12 22:18
Can you show a screenshot? Which app version are you using? do you have the same issue on chrome?

**Comment by LorenzoMcMaster** [comment] 2023-04-12 22:47
I didn't test on chrome but in Brave or firefox it's working. For the screenshot there is not much to show. the round pictures icons are displaying correctly but when you click on the icon, nothing happen on safari. when I do the same click on firefox on the icon, it's shows the picture in small size on.

**Comment by LorenzoMcMaster** [comment] 2023-04-16 20:29
I've found a "workaround' that should help to understand the bug. When I click the mouse button down and I wait 3 seconds before releasing the button, the picture will show on the map. The issue is coming from the speed of the mouse button down / mouse button up timing on safari. Other browsers don't have this issue.

**Comment by bpatrik** [comment] 2023-10-07 14:13
I tried this on a mac with safari (v16.6) and I could not reproduce the issue. I was using the demo app (so the latest code)

I will close this issue as cant fix.

**Closed** 2023-10-07 14:13 UTC
Labels: bug
