### ISSUE TITLE
No response to tapping a photo or video on iPhone 11, iOS 13.4.1

### ISSUE THREAD

**Issue by misterwrong** [bpatrik/pigallery2#155] opened 2020-05-11 07:17 UTC
**Describe the bug**
When I tap on a photo in a collection on an iPhone 11, I expect it to be shown (almost) full screen, but nothing appears to happen. When I tap on the white triangle in a video, I expect it to start playing, but nothing appears to happen either.

This behavior is regardless of the collection, user or whether Safari, Chrome or Firefox is used. The same photos and videos behave as expected an Android phone as well as a notebook.

**Environment (please complete the following information):**
 - OS: Server: Linux 5.6.11,  
 - Browser: Safari, Chrome and Firefox

**Used app version**:
- bpatrik/pigallery2:latest 
- docker version 19.03.8-ce

**Comment by bpatrik** [comment] 2020-05-22 08:10
Thanks for the report. It does not sound good. I'll look into it.

**Comment by macxs** [comment] 2020-08-08 13:05
I‘ve got the same issue on iOS 13.5.1 iPhone Xr having the same setup as @misterwrong but also on the demo instance.

**Comment by helmut72** [comment] 2020-12-08 15:51
It only works when you press with two fingers at the thumbnail, at least on an iPad.

**Comment by FelixUster** [comment] 2021-03-16 11:04
> 
> 
> It only works when you press with two fingers at the thumbnail, at least on an iPad.

After you figured this out, I've tried this within the PiGallery2 Demo and it seems that all buttons and actions are activated by tapping with two fingers.

@bpatrik

**Comment by bpatrik** [comment] 2021-04-04 07:34
This is a duplicate of #155. Lets continue it there.

**Comment by bpatrik** [comment] 2021-04-04 07:44
The issue seems to be with leaflet / yaga-map (library used for showing the map. 
I want to eventually replace it to https://github.com/Asymmetrik/ngx-leaflet or something similar as yaga-map is not well maintained. But that requires the Angular CLI to be updated: https://github.com/Asymmetrik/ngx-leaflet/issues/273 and for that I need to refactor i18n (translation) which will be a lot of work. 

For now, I disabled map preview for IOS (replaced it with an ugly icon). This seems to resolve the issue.

**Comment by macxs** [comment] 2021-04-09 17:10
Thanks a lot! Successfully tested on the demo instance

**Comment by bpatrik** [comment] 2021-05-02 14:18
I updated the maps in #256. 
I quickly tested it on an old iPad. It seems to work. Can you confirm?

**Comment by macxs** [comment] 2021-05-02 15:54
Works perfectly. Huge thanks for your efforts!

**Closed** 2021-05-03 20:47 UTC
Labels: bug
