### ISSUE TITLE
FaceTagging with DigiKam: Fix "No faces available"

### ISSUE THREAD

**Issue by knalltuete86** [bpatrik/pigallery2#696] opened 2023-08-21 16:49 UTC
**Describe the bug**

I started to tag my photos of the past years with face recognition of DigiKam (https://www.digikam.org). After tagging some thousand photos I tried if they show up in PG2 - but no luck.

Due to this I started to compare the XMP-Data of my photos with those of the sample files:

`exiftool -G1 -s -a -XMP-mwg-rs:all x.jpg`

For example, the result of the "Vuk the fox" (https://github.com/bpatrik/pigallery2/blob/master/demo/images/IMG_9516.jpg) is:

_[XMP-mwg-rs]    RegionAppliedToDimensionsW      : 1273
[XMP-mwg-rs]    RegionAppliedToDimensionsH      : 849
[XMP-mwg-rs]    RegionAppliedToDimensionsUnit   : pixel
[XMP-mwg-rs]    RegionRotation                  : -0.02101
[XMP-mwg-rs]    RegionName                      : Vuk the fox
[XMP-mwg-rs]    RegionType                      : Face
[XMP-mwg-rs]    RegionAreaH                     : 0.51884
[XMP-mwg-rs]    RegionAreaW                     : 0.34557
[XMP-mwg-rs]    RegionAreaX                     : 0.65155
[XMP-mwg-rs]    RegionAreaY                     : 0.67901_

**Photo/video (optional) that causes the bug**
Compared to this, the result of my photo is:

_[XMP-mwg-rs]    RegionAppliedToDimensionsW      : 4032
[XMP-mwg-rs]    RegionAppliedToDimensionsH      : 3024
[XMP-mwg-rs]    RegionAppliedToDimensionsUnit   : pixel
[XMP-mwg-rs]    RegionName                      : Name1
[XMP-mwg-rs]    RegionType                      : Face
[XMP-mwg-rs]    RegionAreaX                     : 0.543279
[XMP-mwg-rs]    RegionAreaY                     : 0.442295
[XMP-mwg-rs]    RegionAreaW                     : 0.110367
[XMP-mwg-rs]    RegionAreaH                     : 0.11541
[XMP-mwg-rs]    RegionAreaUnit                  : normalized_

So the only Difference is the `RegionAreaUnit` and `RegionRotation`. By this notice I added the `RegionRotation=0.0` to an sample photo:

`exiftool -xmp:regionrotation+=0.0` 

So the result is as follows:

_[XMP-mwg-rs]    RegionAppliedToDimensionsH      : 3024
[XMP-mwg-rs]    RegionAppliedToDimensionsUnit   : pixel
[XMP-mwg-rs]    RegionAppliedToDimensionsW      : 4032
[XMP-mwg-rs]    RegionAreaH                     : 0.11541
[XMP-mwg-rs]    RegionAreaUnit                  : normalized
[XMP-mwg-rs]    RegionAreaW                     : 0.110367
[XMP-mwg-rs]    RegionAreaX                     : 0.543279
[XMP-mwg-rs]    RegionAreaY                     : 0.442295
[XMP-mwg-rs]    RegionName                      : Name1
[XMP-mwg-rs]    RegionRotation                  : 0.0
[XMP-mwg-rs]    RegionType                      : Face_

After this change, the face appears in PG2 successfully! So it seems the property RegionRotation is required by PG2, but not set by DigiKam. I couldn't figure out if it is possible to write it automatically.

Now I made the following work around:

As I tagged my photos the last days I ran the following command to add the RegionRotation-Tag with value 0:

`find . -type f -regex .*jpg -mtime -5 -exec exiftool -overwrite_original -xmp:regionrotation=0.0 {} \;`

This command finds all *.jpg Files which has been changed within the last 5 days and add's the `RegionRotation`-Tag.

May this help others who are getting into the same issue.

Is it may possible to adjust MetadataLoader.ts in order to assume the value 0 if RegionRotation is not present?

Thanks!

**Comment by bpatrik** [comment] 2023-08-24 20:25
Hi,

I suspect the issue is different. 

Here is the code that parses faces: https://github.com/bpatrik/pigallery2/blob/d64670751cfd5f601c126cf69df89859cf08d4a0/src/backend/model/threading/MetadataLoader.ts#L355-L388

It does not use rotation.

**Comment by knalltuete86** [comment] 2023-08-25 19:40
Dear @bpatrik ,
thanks for your comment. To figure out what's the root cause I compared all metadata of an image before and after adding the RegionRotation-Tag via Exiftool via https://imagemetadatachecker.com:

**XMPToolkit**
_Before_: XMP Core 4.4.0-Exiv2
_After:_ Image::ExifTool 12.40

**SourceFile**
_Before_: IMG_20230121_064515.jpg_original
_After_: IMG_20230121_064515.jpg

**RegionRotation**
_Before_: undefined
_After_: 0

**FileName**
_Before_: IMG_20230121_064515.jpg_original
_After_: IMG_20230121_064515.jpg

**SourceFile** and **FileName** ist different, of course. So the only root cause that the second file works and the original not should be either **RegionRotation** or **XMPToolkit** 

I did check the Source of ExifReader as well, but both Tags could not be found. 

Is there any way to check if the `else if`-Condition is valid for a specific file?

For now I use the workaround above, but of course its not the way it should be.

Thank you in advance!

**Comment by bpatrik** [comment] 2023-08-28 07:44
Can you send  me a smaple photo with the error? So that I can test it?

**Comment by knalltuete86** [comment] 2023-09-04 07:21
Of course, you may have a storage to upload a sample photo to?

**Comment by bpatrik** [comment] 2023-09-04 07:37
People just usually upload them here.

The best would be if you can send a super small, like 1x1px or 10x10px
image that has the issue that you described here. So I can right away add
it to the unit tests.

-- Sorry for being brief, sent from my phone.

**Comment by mblythe86** [comment] 2023-09-20 08:00
For what it's worth, I've been face-tagging with DigiKam as well, and PiGallery2 seems to recognize all my face tags just fine.

**Comment by knalltuete86** [comment] 2023-09-20 11:39
Dear  @mblythe86,

that great to hear. Can you may offer some more information?

- What version of DigiKam are you using?
- Are you using any custom settings?
- What version of PG2 are you using?
- Can you check if your tagged images contain the `RegionRotation`-Tag?


Dear @bpatrik,

sorry I just recognized your last Post right now. Please find a sample photo of "Teddy" enclosed. 

![P1140104](https://github.com/bpatrik/pigallery2/assets/134937302/07d54d4a-ebca-4020-8cd7-aed215f4d38c)

This photo does not include the `RegionRotation`-Tag. While writing this post I just double-checked and found that v1.9.6-edge recognized it correctly. I will keep watching which photos are affected and which not.

**Comment by bpatrik** [comment] 2023-09-20 11:55
Great:)

If you find one, please send me a photo that is broken on the 'edge' build.
Otherwise I will just consider this bug to be fixed

-- Sorry for being brief, sent from my phone.

**Comment by mblythe86** [comment] 2023-09-21 06:14
>    What version of DigiKam are you using?

I've been using the 'appimage' releases for a while, so I tend to stay relatively up-to-date.  Right now, I'm using 8.0.0.  But I see that I have downloads as old as 5.9.0.  I'm sure some of my images have been tagged by these older versions, and they seem to be OK with PiGallery2.

>    Are you using any custom settings?

Not as far as I can tell?  I do have the option checked "Delegate to ExifTool backend all operations to write metadata to files".  IIRC, that's a pretty recent thing, so my old images wouldn't have been written by ExifTool.

>    What version of PG2 are you using?

I'm using the docker image "bpatrik/pigallery2:latest-debian-bullseye" for my 'production' website.  I recently spun up  an instance of "bpatrik/pigallery2:edge-debian-bullseye" to test it out, and didn't notice any difference in recognizing face tags.

>    Can you check if your tagged images contain the RegionRotation-Tag?

I spot-checked some of my photos from the past few years using the `exiftool -G1 -s -a -XMP-mwg-rs:all <image>` command you listed above.  Recent ones have these tags:

```
[XMP-mwg-rs]    RegionAppliedToDimensionsW
[XMP-mwg-rs]    RegionAppliedToDimensionsH
[XMP-mwg-rs]    RegionAppliedToDimensionsUnit
[XMP-mwg-rs]    RegionName
[XMP-mwg-rs]    RegionType
[XMP-mwg-rs]    RegionAreaX
[XMP-mwg-rs]    RegionAreaY
[XMP-mwg-rs]    RegionAreaW
[XMP-mwg-rs]    RegionAreaH
[XMP-mwg-rs]    RegionAreaUnit
```

Older ones have only these tags:

```
[XMP-mwg-rs]    RegionName
[XMP-mwg-rs]    RegionType
[XMP-mwg-rs]    RegionAreaX
[XMP-mwg-rs]    RegionAreaY
[XMP-mwg-rs]    RegionAreaW
[XMP-mwg-rs]    RegionAreaH
[XMP-mwg-rs]    RegionAreaUnit
```

I didn't find any images with `RegionRotation`, but all of mine seem to have `RegionAreaUnit`.  Not sure whether that matters, since the code snippet [here](https://github.com/bpatrik/pigallery2/issues/696#issuecomment-1692359508) doesn't seem to reference `RegionAreaUnit` at all.

**Comment by knalltuete86** [comment] 2023-09-21 14:19
Dear @mblythe86 
thank you for your response. I do use DigiKam 8.1.0, so it should work. I also checked the option "_Delegate to ExifTool backend all operations to write metadata to files_" now and made a first run. Everything work well so far - so I'll keep keep watching.

**Comment by bpatrik** [comment] 2023-10-07 23:13
If I understand correctly this is resolved. So I'm closing this for now. Feel free to reopen if you think otherwise.

**Closed by bpatrik** 2023-10-07 23:13 UTC
Labels: bug, more input needed
