### ISSUE TITLE
Exclude indexing by regex foldername

### ISSUE THREAD

**Issue by lakomyt** [bpatrik/pigallery2#617] opened 2023-02-22 14:18 UTC
I don't want Pigallery to index files related to some metadata.
For example if i have additional folder with metadata named `something.meta` I want to exclude `*.meta` from indexing. Same situation with files.

Wildcard is enough I think, it doesn't have to work like a regular regex.

**Comment by bpatrik** [comment] 2023-02-24 07:08
duplicate of #192.
Lets continue there.

**Closed by bpatrik** 2023-02-24 07:08 UTC
