### ISSUE TITLE
Choose Album Cover

### ISSUE THREAD

**Issue by GiamBoscaro** [bpatrik/pigallery2#329] opened 2021-06-20 19:35 UTC
**Is your feature request related to a problem? Please describe.**
I cannot choose the album cover

**Describe the solution you'd like**
I'd like to be able to choose an album cover from the images inside the album (facebook like)

**Describe alternatives you've considered** (optional)
None

**Comment by wechsler42** [comment] 2021-06-21 12:11
I would like to second this feature request.

**Comment by bpatrik** [comment] 2021-06-22 19:20
This is a duplicate of #80 please follow the conversation there.

**Closed by bpatrik** 2021-06-22 19:20 UTC
