### ISSUE TITLE
child dir "scandir EACCES" prevents the opening of the parrent dir

### ISSUE THREAD

**Issue by Suika** [bpatrik/pigallery2#731] opened 2023-10-02 00:25 UTC
**Note:** Please always try reproducing the issue on the `:edge` build. There is a chance that it was already fixed. If it's an UI issue, you can try reporducing it on the [demo page](https://pigallery2.onrender.com/). 

----------------------------------------------------------------------------------

**Describe the bug**
Let there be a default path in the container that is `/app/data/images` and a `/mnt/collections` NFSv4 client mount on the docker host.
Inside `/mnt/collections` there is folder `drwxr-xr-x  45 1000 1000   45 Sep 10 14:04  OK` and `drwxr-x---   9   831 1200    9 Oct  2 00:07  NOTOK`
Host path `/mnt/collections` is mounted onto `/app/data/images/collections` in the container.

Because the mount is NFSv4, it matter not if the root inside the container or on the host try to access `NOTOK`, it will fail with:
```bash
cd NOTOK/
bash: cd: NOTOK/: Permission denied
```

When trying to access the `collections` folder in pigallery2, it will fail with the following error:
```json
{
    "error": {
        "code": 7,
        "message": "Error during listing the directory",
        "request": {
            "method": "",
            "url": ""
        }
    },
    "result": null
}
```
Just because a single folder in `collections` can not be read by pigallery.

**Photo/video (optional) that causes the bug**
-

**Screenshots (optional)**
-

**Server logs (optional)**

```
10/2/2023, 12:13:26 AM[WARN_] Handled error:
ErrorDTO {
  code: 7,
  message: 'Error during listing the directory',
  details: {
    errno: -13,
    code: 'EACCES',
    syscall: 'scandir',
    path: '/app/data/images/collections/NOTOK'
  },
  request: { method: '', url: '' },
  detailsStr: '[object Object]'
}

```

**Environment (please complete the following information):**
 - OS: SLES15SP5
 - Chrome latest

**Used app version**:
- `bpatrik/pigallery2:latest@sha256:43b6c3bfc6f4141d88b3088250b16b8aad1b3b5f5a48fc676c4df9e19a44c11b`

**Comment by bpatrik** [comment] 2023-10-06 22:30
please check if you can reproduce it on the edge build

**Comment by Suika** [comment] 2023-10-14 03:06
`bpatrik/pigallery2:edge-debian-buster@sha256:8e33bf3846a900d934157765513a01e8e7b54409fb4496a8f0899d094435c068`

In browser console:
```json
{
    "code": 31,
    "message": "Error during listing the directory",
    "request": {
        "method": "",
        "url": ""
    },
    "title": "GENERAL_ERROR"
}
```

Docker Logs:
```
10/14/2023, 2:59:51 AM[WARN_] Handled error:
ErrorDTO {
  code: 31,
  message: 'Error during listing the directory',
  details: {
    errno: -13,
    code: 'EACCES',
    syscall: 'scandir',
    path: '/app/data/images/collections/testfolder/NOTOK'
  },
  request: { method: '', url: '' },
  detailsStr: '[object Object]'
}
```

I changed the path a bit for it not to be so high up. Either way, it still fails and boots me from `your.domain.tld/gallery/collections/testfolder/` into `your.domain.tld/gallery/`

**Comment by bpatrik** [comment] 2023-10-14 14:29
hmm. I'm not sure if I understand your original issue. Does the app have read permission to your folder? If not seeing these errors are work as intended.

Also it seems to be a duplicate of #704 and you can also take a look at #48, #39

**Comment by Suika** [comment] 2023-10-14 16:00
>I'm not sure if I understand your original issue. Does the app have read permission to your folder?
Yes it has permissions to almost all folders, except one. Let me try it again, say you have /app/data/images/collections and in that folder following folders exist: 1,2,3,4,5,6,7,8,9. 
All folders have the right permissions, except "7". "7" is not able to be accessed by the pigallery user. Visiting /app/data/images/collections will trigger pigallery to scan the contents of "collections", encounters a folder it can not read and proceed to error out, booting me into /app/data/images.

Is it intentional that pigallery fails to display directory contents when it can't read a single entry inside the said directory? Or can it be made to ignore EACCES errors, as they are simply permission issues and display the rest of the folder contents?

In regards to the mentioned issues, they are [ENOENT](https://man7.org/linux/man-pages/man3/errno.3.html), non-existing paths. But this is EACCES, a basic permission issue.

**Comment by bpatrik** [comment] 2023-10-14 17:09
Improved on it a bit. Can you check if it resolves your problem?

this should build first: https://github.com/bpatrik/pigallery2/actions/runs/6518926900

**Comment by Suika** [comment] 2023-10-14 19:16
Yup, I see this in the logs:
```
[Error: EACCES: permission denied, scandir '/app/data/images/collections/testfolder/NOTOK'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/app/data/images/collections/testfolder/NOTOK'
}
```

But now I am able to browse the `/app/data/images/collections/testfolder` without being booted into `/app/data/images/collections`. 237e61c fixed the issue.

Works great now, thanks.

**Closed** 2023-10-15 02:26 UTC
Labels: bug, enhancement, more input needed
