### ISSUE TITLE
Job error: TypeError: config.sizes is not iterable when manually run the thumbnail generation

### ISSUE THREAD

**Issue by hajo62** [bpatrik/pigallery2#534] opened 2022-09-01 22:06 UTC
docker image [v1.9.3] on ubuntu 22.04 on RaspberryPi 4

When I manually run the thumbnail generation, I get the error: `Error: Job error: TypeError: config.sizes is not iterable`.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/15800980/188020521-9024cafe-c47b-4ace-8e79-5855e8f29501.png">

When I start the job in the indexing section, it seems to run:
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/15800980/188021109-9842d3b4-6ca6-48a2-977d-1f2e735948a9.png">

**Comment by tilmanginzel** [comment] 2022-09-05 10:56
Seems to be a duplicate of #458 (possible fix is mentioned there)

**Comment by bpatrik** [comment] 2022-12-09 21:53
To my understanding this is fixed. Closing it. Feel free to reopen if you think otherwise.

**Closed by bpatrik** 2022-12-09 21:53 UTC
Labels: bug
