### ISSUE TITLE
[FeatureRequest] - RandomLinks

### ISSUE THREAD

**Issue by ItJustFox** [bpatrik/pigallery2#492] opened 2022-05-23 19:43 UTC
**Is your feature request related to a problem? Please describe.**
Technicaly a little problem, we should be able to make the RandomLink available for no register login

**Describe the solution you'd like**
Make the random link available for poeple not register with an account with a small button like the share to be able to use our pigallry everywhere ?

**Describe alternatives you've considered** (optional)
A share version with random link directly in in other way ? maybe

**Comment by bpatrik** [comment] 2022-06-13 15:03
It seems to be a duplicate of #392

**Closed** 2023-08-05 14:19 UTC
Labels: duplicate
