### ISSUE TITLE
Question: How would I set the folder icon?

### ISSUE THREAD

**Issue by hajo62** [bpatrik/pigallery2#528] opened 2022-08-24 21:58 UTC
Is there a way to specify the icon (photo) which is used in the folder?

**Comment by bpatrik** [comment] 2022-08-30 07:47
There is no way at the moment.

duplicate of #325

**Comment by hajo62** [comment] 2022-08-30 07:58
I was not thinking about the favicon (the one in the browser) but the ones displayed in the folders:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/15800980/187382574-97e3223b-6dfb-4892-beb7-ce05cbe85ee2.png">

**Comment by bpatrik** [comment] 2022-08-30 08:07
Ah that schould be possible, but not individually but rather specifying a search querry under previous ![Screenshot_20220830-100539.png](https://user-images.githubusercontent.com/7512182/187384315-eccd4743-dca8-48bf-9046-86abeac47379.png)

**Comment by hajo62** [comment] 2022-08-30 08:11
_Not individually_ means one rule for all folders?
If yes, I was more thinking on specify an image for each folder instead of that the tool picks one by a common rule. May introduce a `.folder_icon` or `.icon` file which is used for that purpose and not displayed.

**Comment by bpatrik** [comment] 2022-08-30 08:17
You can create a icon.jpg in every folder and then specify in the preview search querry that specific file name. Or you can tag a photo in each folder with a 'cover' tag then specify that tag in the query.

It is not possible to have a cover photo that doesn't show up in the library.

You can also list all your relatives names in the query with an OR relationship and it will pick photos with people on it

**Comment by hajo62** [comment] 2022-08-30 08:23
> You can create a icon.jpg in every folder and then specify in the preview search querry that specific file name. Or you can tag a photo in each folder with a 'cover' tag then specify that tag in the query.

Okay, thanks. Will try that and assume it will do the job.
But: When (re)using a photo within a folder you need to rename that (i.e. to icon.jpg) but than, sorting by name does mix up the order or you need to duplicate the photo which is also not perfect.

So you might rethink about my suggestion as a feature request?!

**Closed** 2022-08-30 08:23 UTC
Labels: duplicate

**Comment by bpatrik** [comment] 2022-08-30 08:32
There is a on open issue with a similar request.
Probably i won't have time for this in the near future. Also it would make
the current solution confusing.


You can use any metadata that the app reads (tags, stars, title, date,
name, etc..) to mark a photo to be the cover photo.

I'm face tagging and staring all my photos. Then my search querry list my
family and requires min Star to be 4.

-- Sorry for being brief, sent from my phone.

**Comment by hajo62** [comment] 2022-08-30 09:22
How would I best specify a tag?
Mostly I use xnview to deal with my photos; there I could modify the XMP or the IPTC information. But none of those attributes is called tag.

**Comment by bpatrik** [comment] 2022-08-30 09:48
I'm not sure how that app works. You can try also look for for keywords. I
think it is stored in iptc.
If you are using windows, explorer can also add tags/keywords

-- Sorry for being brief, sent from my phone.

**Comment by hajo62** [comment] 2022-08-30 21:49
Hhm, added a tag to a photo - on a Mac that could i.e. be done with finder (Mac equiv to Explorer).
But what would I need to rerun that the tag aka keyword is recognized?

**Comment by hajo62** [comment] 2022-09-01 21:59
Asked the community for help: #533
