### ISSUE TITLE
Images folder setting not stored

### ISSUE THREAD

**Issue by tvwerkhoven** [bpatrik/pigallery2#352] opened 2021-08-10 09:16 UTC
**Describe the bug**

When changing `Page Title`, the `Images folder` setting is also changed to the value of `Temp folder`. Changing the value of `Images folder` back does not work, when saving it reverts to the value of `Temp folder`.

Perhaps the value of `Images folder` is internally read from `Temp folder`.

**Photo/video (optional) that causes the bug**

N/A

**Screenshots (optional)**

https://user-images.githubusercontent.com/78742/128841234-cbca8ee2-f8af-4bf6-8260-58ad6bb5607b.mov

**Server logs (optional)**

N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 running Docker container without nginx
 - Browser: Safari on MacOS

**Used app version**:
- latest-debian-buster

**Comment by tvwerkhoven** [comment] 2021-08-10 09:26
Workaround seems to be to manually change `folder` in `./pigallery/config/config.json`.

**Comment by rhatguy** [comment] 2021-08-10 12:52
+1 for this.  This was happening to me on a docker based install on a
Gentoo linux host.  Changing the config.json outside of the container
seemed to work and I haven't touched the folders in the gui since.

**Comment by bpatrik** [comment] 2021-09-23 22:01
Thanks, I should fix this.

**Comment by bpatrik** [comment] 2021-09-23 22:01
probably a duplicate of #311

**Comment by peterge1998** [comment] 2021-10-05 19:46
Something similar happend to me. I really like the software.
I describe my problem:
I have this running as a docker container on truenas scale. My images folder is set up to be `/mnt/main/photos`.
After i stop and start the container, it is showing the path of my tmp folder in settings and is showing a weird folder structure with multiple tc folders and multiple images.
I hope you are able to fix this asap. If you need more logs, details, etc. just ask!

**Comment by Nerdiyde** [comment] 2021-12-09 20:22
+1 from me.
Could observe this on my setup as well (Docker container via portainer on raspbian)
Let me know if I should test/verify anything.
(Nevertheless huge thanks for this awesome piece of software. :) )

**Comment by bpatrik** [comment] 2021-12-11 15:25
I took a look. I think this is not an issue since this commit: https://github.com/bpatrik/pigallery2/commit/41975f72a18f985cae27b1bdb6b31c7379b0d87c

It might not be in the latest release, so you can only test it with the nightly build.

**Closed** 2021-12-11 15:25 UTC
Labels: bug
