### ISSUE TITLE
Metadata issue IOS14

### ISSUE THREAD

**Issue by psl2806** [bpatrik/pigallery2#206] opened 2020-11-28 10:31 UTC
On IOS14 navigation halts when there is GPX data in pictures. Older albums without GPX data don’t have this issue. Disbaling the Map and the Meta file settings option is an option.
The issue does not occur on Windows 10, Raspbian Buster or older IOS versions.
So I’m not sure if this is a Pigallery2 issue or an IOS issue.

**Comment by bpatrik** [comment] 2020-12-25 19:03
Hi,

Thanks for the report. I'll try to check it, but I do not have any apple device.

**Comment by bpatrik** [comment] 2021-04-02 09:19
Do you only see this issue on IOS 14? I tested it on an older model and could not reproduce

**Comment by bpatrik** [comment] 2021-04-04 07:34
This is a duplicate of #155. Lets continue it there.

**Closed by bpatrik** 2021-04-04 07:34 UTC
Labels: bug
