### ISSUE TITLE
Add url base option in config.json

### ISSUE THREAD

**Issue by studioai** [bpatrik/pigallery2#7] opened 2018-05-10 08:40 UTC
I have a domain from a free ddns service and want to set a reverse proxy on pigalley2.

```
location /gallery/
{
        proxy_set_header    X-Real-IP    $remote_addr;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_pass    http://127.0.0.1:10080/;
}
```

I tried with above nginx config. All .js file's path is rewritten to root.

![image](https://user-images.githubusercontent.com/11453050/39860679-1f2d6848-5479-11e8-82b9-aac6b64e7621.png)

If there be a url base option like other web apps, Reverse proxy config will be much easier.

**Comment by bpatrik** [comment] 2018-05-10 14:27
Hi,
I'll check the problem in the next few days.

(As on OFF topic I can recommend you an alternative DNS sollution:
* http://www.duckdns.org/ is 100% free, no advertisements, no monthly 'click here to renew' mails. 
* free domain names : http://www.freenom.com/en/index.html?lang=en and you can use something like [this ](https://gist.github.com/a-c-t-i-n-i-u-m/bc4b1ff265b277dbf195) to make it dynamic )

**Comment by bpatrik** [comment] 2018-05-12 16:53
Hi,
I've added it with the [latest commit ](https://github.com/bpatrik/pigallery2/commit/babf2fc584406b3260b97e352bb928329c9b3835). It will be part of the next release. 

In the meantime you can install from source:
```bash 
cd ~
wget https://github.com/bpatrik/pigallery2/archive/master.zip
unzip master.zip
cd pigallery2 # enter the unzipped directory
npm install
```

**Comment by bpatrik** [comment] 2018-05-14 22:36
Hi,

I'll try to reproduce the error.
In the mean time, can you make sure that the `npm install` runs without an error?
This `Cannot find module '/opt/pigallery2/backend/index'` usually means that the `*.ts` files were not compiled to `*.js` files.

**Comment by studioai** [comment] 2018-05-15 09:00
[nohup.out.txt](https://github.com/bpatrik/pigallery2/files/2004134/nohup.out.txt)

This is the log from 'nohup npm install &'. It seems to be failing on the install process.

**Comment by bpatrik** [comment] 2018-05-15 15:14
Hi,

I removed `phantomjs` from the dependencies, now It should install on a raspberry (tested on rpi3, raspbian).
Although i had issues building the angular frontend, because the it ate up all my ram and swap. 
If you have the same issue, you can try:
a) increasing the swap
b) building it on a stronger machine:
  ```bash
  cd ~
  wget https://github.com/bpatrik/pigallery2/archive/master.zip
  unzip master.zip
  cd pigallery2-master # enter the unzipped directory
  npm install
  npm run build-release
  ```
  now you should have a `release` folder that you can copy to the rpi
c) I'll have a new release this or next week, you can wait for that

**Comment by studioai** [comment] 2018-05-16 05:34
I built it on my PC. It works perfectly! Thank you for your effort  and works!

**Closed** 2018-05-16 05:34 UTC
