### ISSUE TITLE
Fixed breadcrumbs

### ISSUE THREAD

**Issue by mariusg0000** [bpatrik/pigallery2#499] opened 2022-06-15 05:03 UTC
It would be nice if the breadcrumbs was fixed and did not scroll with the contents, especially if the mouse or touchscreen is used for navigation.

**Comment by bpatrik** [comment] 2022-12-10 00:03
sort of duplicate of https://github.com/bpatrik/pigallery2/issues/27

**Comment by bpatrik** [comment] 2022-12-10 00:04
lets continue there. closing this.

**Closed by bpatrik** 2022-12-10 00:04 UTC
